before_script:
  - docker stop telegram-mopidy-bot || true
  - docker rm telegram-mopidy-bot || true

humpink:
  script:
  - cp /home/eljenso/mopidy-bot.txt .
  - docker build -t telegram-mopidy-bot .
  - docker run -d -v /etc/localtime:/etc/localtime --name telegram-mopidy-bot telegram-mopidy-bot
  type: deploy
  tags:
  - humpink
  - shell
