before_script:
  - docker stop telegram-mopidy-bot || true
  - docker rm telegram-mopidy-bot || true

humpink:
  script:
  - cp /tmp/mopidy-bot.txt ./config.txt
  - docker build -t telegram-mopidy-bot .
  - docker run -d --name telegram-mopidy-bot telegram-mopidy-bot
  type: deploy
  tags:
  - humpink
  - shell
